[colors.normal]
black = "#151515"
blue = "#b0b0b0"
cyan = "#828282"
green = "#999999"
magenta = "#a4a4a4"
red = "#8e8e8e"
white = "#f0f0f0"
yellow = "#777777"

[colors.primary]
background = "#151515"
foreground = "#f0f0f0"

[font]
size = 8

[font.bold]
family = "JetBrains Mono"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrains Mono"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[terminal.shell]
program = "/bin/zsh"

[window.padding]
x = 20
y = 15
